version: '3.8'

services:
  web:
    build: .
    container_name: tadevosyan-it-local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - N8N_WEBHOOK_URL=http://localhost:5678/webhook/test # Локальный n8n